"""
Author: Keerthik Muruganandam
Topic: Rosalind.info Bioinformatics Armory Solutions
Language: Python
"""
from Bio.Seq import Seq

def ini(dna):
    seq = Seq(dna)
    print(seq.count("A"), " ")
    print(seq.count("C"), " ")
    print(seq.count("G"), " ")
    print(seq.count("T"))

################ MAIN RUN ###################
if __name__ == '__main__':
    ini("AACTGCATAATACGAAAATGGGACACCGGCAAGCGGCCCTACTTAGGCGGACCGAGGTATCAAATGTGAGAGATGAAAGCGTCCAGACCAGTACCAGTTCGACTGCACACATAGAATACAGAGTCGTTGGGTCTCCCCATACCTTTGGCATGCTAACCAGGACACGTTGACATCCGTTGACACTGAGAGATCCGCGAAGTTTGTTCTTGACAAGAGGGTCGTATGAGTTTTGCGCGATTCCACACGGCCACCGCTCTCGTAATCTTAATGACCATAATGTTCATACTCCTAATCTGGGTCCAGCGCATATTATCGAGTTTGGGCGTATATCGATCTTGCCTCATTTCAAGCAGTTAGACTTCAAATGTTAGACCGTCGATCCTTCCCACTTTCATGCTTCCCCATCTTCTAGAGTATATTACTTAACAGCCATCTACATGTCCAGGAACCCTGTACTGAAGCCACGAGTATAGGTGCCAGAAGGTTCCCTCTGTCGCTTAATAATCCTAACGGTGCCCGGACGTTGTCCTTGTAGCAGATTGGCCACTTCTACATGCGTCATCATTCGACTAACCGGTATTCCGTAGAGAAACGTAACCATGAGATTGTGTCGCAGAGATCAACGAGTCAAGTCCACCAACTTCTCTTTACCTCAAGGGCAGTCATGCAGACGTCCTCCCCCTTTGCAACGGCAGAACGTGCGGGTGCTCACGTATGCCGGCCCACGGCAGCCCACAAGCTGGCGCGACTGTCCTACAGTGAGAACAATTCTGTTATATTCGAGTTCAACGTTTCGCTGTCACAGTCCCCCACGCGAGAGGCTTAGGTGCGTTGCATGTGACAGCCTTCTGGTTTGCTGGTCAGCTGTCTTGTCGATAAGTACGTCGAGTCTAACGGTAATAGATTACAATCGGACTGGACCTGGTTAATATCGGGGACTCTATACAACGCGGCTTGGACAGCTATAGCAATTGCCTTGA")
